### ISSUE TITLE
是否只装ext-ffi一个扩展就够了？

### ISSUE THREAD

**Issue by aszx0413** [pkg6/wxwork-finance.php#2]
是否只装ext-ffi一个扩展就够了？然后composer完直接可以使用对吗？
因为在ext-ffi这个扩展安装不上，所以想了解还需要继续钻研解决这个扩展？

Thanks

**Comment by chihqiang** [comment]
是的装上扩展就可以使用的，推荐使用ext-wxwork_finance_sdk方式
