### ISSUE TITLE
程序再实例化sdk时报502错误

### ISSUE THREAD

**Issue by saucerman** [pkg6/wxwork-finance.php#3]
程序执行到下图位置时报502错误
![图片](https://github.com/user-attachments/assets/2b9aead7-6661-4fe4-9173-18272408b62c)

**Comment by saucerman** [comment]
cli 运行时报错：Segmentation fault

**Comment by chihqiang** [comment]
你别截代码报错位置，你要截报错内容

**Comment by chihqiang** [comment]
这个地方如果报错 大概率是 你没有安装`ext-wxwork_finance_sdk`
